### ISSUE TITLE
Share the source

### ISSUE THREAD

**Issue by karimone** [aviddot/Pancakeswap-sniping-bot-demo#1]
I'm looking for some example on python API for pancakeswap but I see that you're sharing only the exe.

**Comment by ipxs123** [comment]
He is not sharing source, so it's can be scam.

**Comment by aviddot** [comment]
Yes it can be, in the end it's a matter of trust 😅. Im doing it this was because my bots have been stolen and resold before.

And security is indeed an issue, cant really do something about it. 
The only recommendation I can give you is using a new wallet with not too much bnb to test the bot, use wireshark to check what packets the bot sends or reverse engineer the exe
